export const dynamic = 'force-dynamic';
import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { getSession } from '@/lib/auth/jwt';
import crypto from 'crypto';

/**
 * GET /api/admin/company-keys
 * Lists all company API keys generated by admins.
 */
export async function GET() {
    try {
        const session = await getSession();
        if (!session?.userId) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const supabase = createClient();
        const { data: adminUser } = await supabase
            .from('users')
            .select('role')
            .eq('id', session.userId)
            .single();

        if (!adminUser || adminUser.role !== 'admin') {
            return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
        }

        const admin = createAdminClient();
        const { data: keys, error } = await admin
            .from('api_keys')
            .select('*')
            .ilike('name', 'company:%')
            .order('created_at', { ascending: false });

        if (error) throw error;

        // Mask the keys for safe UI display (show prefix and last 4 chars)
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const maskedKeys = (keys || []).map((k: any) => {
            const raw = k.api_key || '';
            const masked = raw.length > 16 
                ? `${raw.slice(0, 12)}...${raw.slice(-4)}`
                : '••••••••••••••••';
            return {
                id: k.id,
                name: k.name?.replace(/^company:/, '') || 'Company Key',
                masked_key: masked,
                status: k.status,
                usage_count: k.usage_count || 0,
                last_used_at: k.last_used_at,
                created_at: k.created_at,
            };
        });

        return NextResponse.json({ success: true, keys: maskedKeys });
    } catch (err: any) {
        console.error('[GET /api/admin/company-keys] Error:', err);
        return NextResponse.json({ error: err.message }, { status: 500 });
    }
}

/**
 * POST /api/admin/company-keys
 * Generates a new company API key.
 * ONLY authenticated admins can trigger this.
 */
export async function POST(req: Request) {
    try {
        const session = await getSession();
        if (!session?.userId) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const supabase = createClient();
        const { data: adminUser } = await supabase
            .from('users')
            .select('role')
            .eq('id', session.userId)
            .single();

        if (!adminUser || adminUser.role !== 'admin') {
            return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
        }

        const body = await req.json().catch(() => ({}));
        const companyName = (body.company_name || 'Main Company').trim();

        // Generate 256-bit cryptographically secure token
        const randomHex = crypto.randomBytes(24).toString('hex');
        const newApiKey = `rf_comp_live_${randomHex}`;

        const admin = createAdminClient();
        const { data: inserted, error } = await admin
            .from('api_keys')
            .insert({
                user_id: session.userId,
                api_key: newApiKey,
                name: `company:${companyName}`,
                status: 'active',
                usage_count: 0,
                usage_limit: 50000,
            })
            .select()
            .single();

        if (error) throw error;

        return NextResponse.json({
            success: true,
            message: 'Company API key generated successfully. Copy it now, as it cannot be retrieved again in full.',
            apiKey: newApiKey,
            keyDetails: {
                id: inserted.id,
                name: companyName,
                status: inserted.status,
                created_at: inserted.created_at,
            },
        });
    } catch (err: any) {
        console.error('[POST /api/admin/company-keys] Error:', err);
        return NextResponse.json({ error: err.message }, { status: 500 });
    }
}

/**
 * DELETE /api/admin/company-keys
 * Revokes an existing company API key.
 */
export async function DELETE(req: Request) {
    try {
        const session = await getSession();
        if (!session?.userId) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const supabase = createClient();
        const { data: adminUser } = await supabase
            .from('users')
            .select('role')
            .eq('id', session.userId)
            .single();

        if (!adminUser || adminUser.role !== 'admin') {
            return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
        }

        const { searchParams } = new URL(req.url);
        const keyId = searchParams.get('id');

        if (!keyId) {
            return NextResponse.json({ error: 'Missing key ID' }, { status: 400 });
        }

        const admin = createAdminClient();
        const { error } = await admin
            .from('api_keys')
            .update({ status: 'revoked' })
            .eq('id', keyId);

        if (error) throw error;

        return NextResponse.json({ success: true, message: 'Company API key has been revoked.' });
    } catch (err: any) {
        console.error('[DELETE /api/admin/company-keys] Error:', err);
        return NextResponse.json({ error: err.message }, { status: 500 });
    }
}
